language: php

env:
  -

php:
  - 5.3
  - 5.4
  - 5.5

install:
  - composer self-update
  - composer install --dev

script:
  - ./bin/phpspec run

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage
